name:  Update images

on: 
  push:
  
  workflow_dispatch :  
  

jobs:
  update-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update images
      run: |
        # Find all markdown files in the repository
        find . -type f -name "*.md" | while read filename; do
          # Check if the file contains the old image URL
          if grep -q 'https://raw.githubusercontent.com/SummerSec/Images/main/' "$filename"; then
            # Replace the old URL with the new URL
            sed -i 's/https:\/\/raw\.githubusercontent\.com\/SummerSec\/Images\/main\//https:\/\/img\.sumsec\.me\//g' "$filename"
          fi
        done

    - name: Commit Replace README
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          branch: ${{ github.event.release.target_commitish }}
          commit_message:  Replace Images Links
          file_pattern: .
